version: '3.7'

services:
    frappe:
        image: bench:latest
        # command: bash -c "sleep infinity"
        volumes: 
            - ..:/workspace:cached
        working_dir: /workspace/development
        ports:
            - "8000-8005:8000-8005"
            - "9000-9005:9000-9005"

    mariadb:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: admin@123 #Security at its best
        volumes:
            - mariadb_vol:/var/lib/mysql
        command:
            - --collation-server=utf8mb4_unicode_ci
            - --character-set-server=utf8mb4
            #- --character-set-client-handshake = FALSE
        # restart: always
        # ports:
        #     - "3306:3306"

    redis:
        image: "redis:alpine"
        hostname: redis
        # ports:
        #     - "6379:6379"
        volumes:
            - redisdata:/data
        # restart: always



volumes:
    mariadb_vol:
    redisdata: